### ISSUE TITLE
Couples mask bug??

### ISSUE THREAD

**Issue by ChristopherTylerGale** [coolAlias/ZeldaSwordSkills#48] opened 2015-10-26 08:39 UTC
I've had next to no problems, except for a bug that seemingly occurs only while wearing the couples mask I've checked this 4 times, only crashing around 5 seconds after putting on the mask.

Might be related to other mods I use, but here is the crash report. From what I can understand it appears to be a render issue. I'll continue playing around with the mods I have to see if they are the problem, but I'm sure it's ZSS that causes it.

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 194042440 bytes (185 MB) / 593149952 bytes (565 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1502 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1502.jar) 
	UCHIJAAAA	Forge{11.14.3.1502} [Minecraft Forge] (forge-1.8-11.14.3.1502.jar) 
	UCHIJAAAA	PlayerAPI{1.1} [Player API] (minecraft.jar) 
	UCHIJAAAA	SmartCore{1.1} [Smart Core] (minecraft.jar) 
	UCHIJAAAA	zeldaswordskills{1.8-3.0.3b} [Zelda Sword Skills] (1.8-zeldaswordskills-3.0.3b.jar) 
	UCHIJAAAA	antiqueatlas{4.2.7-1.8} [Antique Atlas] (antiqueatlas-4.2.7-1.8.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.8.x.jar) 
	UCHIJAAAA	SmartMoving{16.0.1} [Smart Moving] (SmartMoving-1.8-16.0.1.jar) 
	UCHIJAAAA	SmartRender{2.1} [Smart Render] (SmartRender-1.8-2.1.jar) 
	Loaded coremods (and transformers): 
SmartCorePlugin (SmartCore-1.8-1.1.jar)
  net.smart.core.SmartCoreTransformer
PlayerAPIPlugin (PlayerAPI-1.8-1.1.jar)
  api.player.forge.PlayerAPITransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3345' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: 1.8-Forge11.14.3.1502
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3345, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by coolAlias** [comment] 2015-10-31 01:26
Thanks, this issue is already fixed for the next release. It only affected 1.8.

**Comment by coolAlias** [comment] 2015-11-14 07:43
@ChristopherTylerGale Can you post the full crash log please?

**Comment by coolAlias** [comment] 2016-02-08 05:05
Closing this due to no further information and being unable to reproduce it.

**Closed by coolAlias** 2016-02-08 05:05 UTC
Labels: 1.8, bug, more info required
