### ISSUE TITLE
Bomb Flower Causing Shut Down?

### ISSUE THREAD

**Issue by coraxsa** [coolAlias/ZeldaSwordSkills#39] opened 2015-06-29 20:49 UTC
Whenever I come across bomb flowers by lava I get a weird issue where the visual sight of the flower plants I can pick up appears and starts growing in massive groups of 64. This is just having approached near the unbroken and untouched ordinal plants. It causes severe lag which eventually causes a crash.

**Comment by coolAlias** [comment] 2015-07-05 22:52
I cannot reproduce this issue. Can you get it to happen with only ZSS (which version?) and a new world?

**Comment by coraxsa** [comment] 2015-07-14 21:12
It happens in all the 7.10 versions unfortunately. And it happens in every world. Mind you, uninstalling and playing then reinstalling fixes that world for a while. But every new world has that same problem.

**Comment by coraxsa** [comment] 2015-07-14 21:13
Is it possible to remove bomb flowers from the game using the config?

**Comment by coolAlias** [comment] 2015-07-15 01:31
Oh, you're on 1.7.10 - I was testing 1.8. Still, I just tried again and can't get it to do anything other than what it should.

Can you post the crash log on pastebin?

Also, are you sure it's my mod? Because in ZSS, you can't pick up more than one bomb flower at a time - they don't stack.

**Comment by coraxsa** [comment] 2015-07-15 22:49
The thing is that they only seem to exsist as a visual thing, not something I can pick up. Is there not a way to disable them then? Because I love this mod but I really can't use it with this weird glitch.

**Comment by coolAlias** [comment] 2015-07-16 02:08
I can make a config, but I'd much prefer to fix it for real. No one else has reported anything like this - what other mods do you have installed? Can you reproduce it with only ZSS?

**Comment by coraxsa** [comment] 2015-07-18 06:26
I doubt I can, mostly because I have too many mods to uninstall it. But I have a new mod pack and launcher with different mods and I'm going to see if it still causes the same issues. If so I will obtain the crash report and a screen shot.

**Comment by coolAlias** [comment] 2015-07-22 02:37
Has the issue been resolved, then?

**Comment by coolAlias** [comment] 2015-08-02 20:39
I'm marking this as resolved since there is no further confirmation of this bug nor any steps that allow me to reproduce it.

**Closed by coolAlias** 2015-08-02 20:39 UTC
Labels: 1.7.10, bug
